"""Initial migration: create worldbank tables

Revision ID: 0ffb56181289
Revises: 
Create Date: 2026-03-26 13:39:27.428924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffb56181289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_metricas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=False),
    sa.Column('registros_guardados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=False),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_metricas_fecha_ejecucion'), 'etl_metricas', ['fecha_ejecucion'], unique=False)
    op.create_table('worldbank_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('pais_code', sa.String(length=10), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('indicador', sa.String(length=255), nullable=False),
    sa.Column('indicador_code', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('fuente', sa.String(length=100), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pais_anio', 'worldbank_registros', ['pais', 'anio'], unique=False)
    op.create_index('idx_pais_indicador_anio', 'worldbank_registros', ['pais', 'indicador', 'anio'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_anio'), 'worldbank_registros', ['anio'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_fecha_extraccion'), 'worldbank_registros', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_indicador'), 'worldbank_registros', ['indicador'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_indicador_code'), 'worldbank_registros', ['indicador_code'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_pais'), 'worldbank_registros', ['pais'], unique=False)
    op.create_index(op.f('ix_worldbank_registros_pais_code'), 'worldbank_registros', ['pais_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worldbank_registros_pais_code'), table_name='worldbank_registros')
    op.drop_index(op.f('ix_worldbank_registros_pais'), table_name='worldbank_registros')
    op.drop_index(op.f('ix_worldbank_registros_indicador_code'), table_name='worldbank_registros')
    op.drop_index(op.f('ix_worldbank_registros_indicador'), table_name='worldbank_registros')
    op.drop_index(op.f('ix_worldbank_registros_fecha_extraccion'), table_name='worldbank_registros')
    op.drop_index(op.f('ix_worldbank_registros_anio'), table_name='worldbank_registros')
    op.drop_index('idx_pais_indicador_anio', table_name='worldbank_registros')
    op.drop_index('idx_pais_anio', table_name='worldbank_registros')
    op.drop_table('worldbank_registros')
    op.drop_index(op.f('ix_etl_metricas_fecha_ejecucion'), table_name='etl_metricas')
    op.drop_table('etl_metricas')
    # ### end Alembic commands ###
